server:
  port: 18086
spring:
  application:
    name: comet-sequence-provider
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  redis:
    host: 10.7.25.206
    lettuce:
      pool:
        max-idle: 8
    port: 18888
logging:
  level:
    root: INFO
    com:
      dcits: INFO
      dcits.comet.uid: DEBUG
  path: ./logs
com:
  alipay:
    sofa:
      rpc:
        registry-address: zookeeper://10.7.25.201:2282
  dcits:
    uid:
      datasource:
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        driver-class-name: com.mysql.jdbc.Driver
        idle-timeout: 30000
        jdbc-url: jdbc:mysql://10.7.25.205/workflow?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        max-lifetime: 1800000
        max-pool-size: 2
        min-idle: 1
        password: 123456
        pool-name: uidhikari
        username: rb
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://10.7.25.206:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

